[client]
showSidebarNavigation = false

[theme]
primaryColor="#4170f2"
backgroundColor="#2C323C"
secondaryBackgroundColor="#22252A"
textColor="#f0f0f0"

# Widgets
borderColor = "#767171"

# Base text
font = "'Open Sans':https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
baseFontWeight = 400
baseFontSize = 14

# Heading text
headingFont = "'Open Sans':https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
headingFontWeights = [600, 300, 600]
headingFontSizes = ["3rem", "2rem", "1rem"]

